all:
    g++ ./servers/testliveServer.cpp ./servers/liveServer.cpp ./servers/simpleServer.cpp ./sockets/bindingSocket.cpp ./sockets/listeningSocket.cpp ./sockets/simpleSocket.cpp -o ./testliveServer.exe -lws2_32

run:
    ./servers/testliveServer.exe